import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AiDemoService } from '../../../services/ai-demo.service';

@Component({
  selector: 'app-ai-study-plan',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="study-plan-page py-4 bg-light min-vh-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="text-center mb-5">
              <div class="plan-icon mx-auto mb-3"><i class="bi bi-calendar-check-fill fs-2 text-white"></i></div>
              <h3 class="fw-bold">AI Study Plan Generator</h3>
              <p class="text-muted">পরীক্ষার তারিখ ও দুর্বল বিষয় জানান — AI আপনার পড়ার রুটিন তৈরি করবে!</p>
            </div>

            <!-- Input Form -->
            <div class="card border-0 shadow-sm mb-4" style="border-radius:20px" *ngIf="!generatedPlan">
              <div class="card-body p-5">
                <div class="row g-4">
                  <div class="col-md-6">
                    <label class="form-label fw-medium">আপনার Class:</label>
                    <select class="form-select" [(ngModel)]="selectedClass">
                      <option *ngFor="let c of [6,7,8,9,10]" [value]="c">Class {{ c }}</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label class="form-label fw-medium">পরীক্ষার তারিখ:</label>
                    <input type="date" class="form-control" [(ngModel)]="examDate" [min]="minDate">
                  </div>
                  <div class="col-12">
                    <label class="form-label fw-medium">দুর্বল বিষয়গুলো নির্বাচন করুন:</label>
                    <div class="d-flex flex-wrap gap-2">
                      <div *ngFor="let s of allSubjects" class="form-check subject-check">
                        <input type="checkbox" class="form-check-input" [id]="'sub_' + s.id" [(ngModel)]="s.checked">
                        <label class="form-check-label subject-label" [for]="'sub_' + s.id"
                               [class.selected]="s.checked"
                               [style.borderColor]="s.checked ? s.color : ''"
                               [style.background]="s.checked ? s.color + '20' : ''">
                          <i class="bi me-1" [class]="s.icon" [style.color]="s.color"></i>
                          {{ s.name }}
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="col-12">
                    <label class="form-label fw-medium">প্রতিদিন কত ঘন্টা পড়তে পারবেন?</label>
                    <div class="d-flex align-items-center gap-3">
                      <input type="range" class="form-range flex-grow-1" [(ngModel)]="dailyHours" min="1" max="8">
                      <span class="fw-bold fs-5 text-primary">{{ dailyHours }}h</span>
                    </div>
                  </div>
                </div>

                <button class="btn btn-warning btn-lg w-100 fw-bold rounded-pill mt-4" (click)="generatePlan()" [disabled]="isGenerating || !examDate">
                  <span *ngIf="isGenerating" class="spinner-border spinner-border-sm me-2"></span>
                  <i *ngIf="!isGenerating" class="bi bi-magic me-2"></i>
                  {{ isGenerating ? 'Generating Plan...' : 'Generate AI Study Plan' }}
                </button>
              </div>
            </div>

            <!-- Generated Plan -->
            <div *ngIf="generatedPlan" class="card border-0 shadow-sm" style="border-radius:20px; overflow:hidden">
              <div class="card-header p-4 text-white" style="background: linear-gradient(135deg, #1d3557, #2d6a4f)">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <h5 class="fw-bold mb-1">📅 Your Personalized Study Plan</h5>
                    <small class="opacity-75">Generated by EduCenter AI</small>
                  </div>
                  <button class="btn btn-outline-light btn-sm rounded-pill" (click)="generatedPlan = ''">
                    <i class="bi bi-arrow-clockwise me-1"></i>Regenerate
                  </button>
                </div>
              </div>
              <div class="card-body p-4">
                <div class="plan-content" [innerHTML]="formatPlan(generatedPlan)"></div>

                <!-- Action Buttons -->
                <div class="d-flex gap-2 flex-wrap mt-4">
                  <button class="btn btn-primary rounded-pill" (click)="savePlan()">
                    <i class="bi bi-bookmark-fill me-2"></i>Save Plan
                  </button>
                  <button class="btn btn-success rounded-pill" (click)="printPlan()">
                    <i class="bi bi-printer me-2"></i>Print
                  </button>
                  <button class="btn btn-warning rounded-pill" (click)="generatedPlan = ''">
                    <i class="bi bi-arrow-clockwise me-2"></i>Customize
                  </button>
                </div>

                <!-- Saved Confirmation -->
                <div *ngIf="isSaved" class="alert alert-success mt-3 rounded-3">
                  <i class="bi bi-check-circle me-2"></i>Plan saved to your profile!
                </div>
              </div>
            </div>

            <!-- Tips Section -->
            <div class="card border-0 shadow-sm mt-4" style="border-radius:16px">
              <div class="card-body p-4">
                <h6 class="fw-bold mb-3">💡 Effective Study Tips</h6>
                <div class="row g-3">
                  <div class="col-md-6" *ngFor="let tip of studyTips">
                    <div class="d-flex gap-2 align-items-start">
                      <span class="fs-5 flex-shrink-0">{{ tip.icon }}</span>
                      <div>
                        <div class="fw-semibold small">{{ tip.title }}</div>
                        <div class="text-muted small">{{ tip.desc }}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .plan-icon { width: 70px; height: 70px; background: linear-gradient(135deg, #f4a261, #e76f51); border-radius: 20px; display: flex; align-items: center; justify-content: center; }
    .subject-check .subject-label { padding: 8px 16px; border: 2px solid #dee2e6; border-radius: 25px; cursor: pointer; display: inline-flex; align-items: center; font-size: 0.85rem; transition: all 0.15s; }
    .subject-check .subject-label.selected { font-weight: 600; }
    .subject-check .form-check-input { display: none; }
    .plan-content { font-family: 'Inter', sans-serif; line-height: 1.8; }
  `]
})
export class AiStudyPlanComponent {
  selectedClass = 9;
  examDate = '';
  dailyHours = 3;
  generatedPlan = '';
  isGenerating = false;
  isSaved = false;
  minDate = new Date().toISOString().split('T')[0];

  allSubjects = [
    { id: 'math', name: 'Mathematics', icon: 'bi-calculator', color: '#2d6a4f', checked: false },
    { id: 'physics', name: 'Physics', icon: 'bi-lightning', color: '#f4a261', checked: false },
    { id: 'english', name: 'English', icon: 'bi-translate', color: '#457b9d', checked: false },
    { id: 'bangla', name: 'Bangla', icon: 'bi-book', color: '#e63946', checked: false },
    { id: 'science', name: 'Science', icon: 'bi-flask', color: '#6a4c93', checked: false },
    { id: 'chemistry', name: 'Chemistry', icon: 'bi-droplet', color: '#2a9d8f', checked: false },
    { id: 'ict', name: 'ICT', icon: 'bi-laptop', color: '#0077b6', checked: false },
  ];

  studyTips = [
    { icon: '⏰', title: 'Pomodoro Technique', desc: '25 min study + 5 min break = 1 Pomodoro. Do 4 rounds then take a long break.' },
    { icon: '📝', title: 'Active Recall', desc: 'Close the book and try to recall what you just read — most effective memory technique.' },
    { icon: '🔄', title: 'Spaced Repetition', desc: 'Review yesterday\'s topics briefly each day. This beats cramming.' },
    { icon: '😴', title: 'Sleep Properly', desc: 'Studying while sleep-deprived is 40% less effective. Aim for 7-8 hours.' },
    { icon: '📱', title: 'No Phone During Study', desc: 'Keep your phone in another room. Just 1 notification halves your focus.' },
    { icon: '🥗', title: 'Eat Light', desc: 'Heavy meals cause drowsiness. Eat light and stay hydrated while studying.' },
  ];

  constructor(private aiService: AiDemoService) {}

  generatePlan(): void {
    this.isGenerating = true;
    setTimeout(() => {
      const weak = this.allSubjects.filter(s => s.checked).map(s => s.name);
      this.generatedPlan = this.aiService.generateStudyPlan(this.selectedClass, this.examDate, weak);
      this.isGenerating = false;
    }, 1800);
  }

  formatPlan(text: string): string {
    return text
      .replace(/##\s*(.*)/g, '<h5 class="fw-bold text-primary mt-3 mb-2">$1</h5>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\|(.*?)\|/g, (m) => m) // preserve table
      .replace(/\n/g, '<br>');
  }

  savePlan(): void {
    this.isSaved = true;
    setTimeout(() => this.isSaved = false, 3000);
  }

  printPlan(): void { window.print(); }
}
